#!/bin/zsh
set -e

autoload colors
if [[ "$terminfo[colors]" -gt 8 ]]; then
    colors
fi
for COLOR in RED GREEN YELLOW BLUE MAGENTA CYAN BLACK WHITE; do
    eval $COLOR='$fg_no_bold[${(L)COLOR}]'
    eval BOLD_$COLOR='$fg_bold[${(L)COLOR}]'
done
eval RESET='$reset_color'

TASKFILE=/tmp/$$.tasks.tmp
ASANACMD=./asana

function main() {
    while show_tasks; do
        clear
    done
}

function show_task() {
    clear
    $ASANACMD task $1 -v 

    echo "${CYAN}[co]${RESET}mment | ${CYAN}[do]${RESET}ne | ${CYAN}[ass]${RESET}ign | assign to ${CYAN}[me]${RESET}"
    echo -n "? "
    read r
    dotaskcommand $r $1
}

function dotaskcommand() {
    case "$1" in
        "co")
            $ASANACMD comment $2
            ;;
        "do")
            complete_task $2
            ;;
        "ass")
            assign_task $2
            ;;
        "me")
            assign_task_to_me $2
            ;;
    esac
}

function complete_task() {
    $ASANACMD done $1
    clear_cache
}

function assign_task_to_me() {
    $ASANACMD me $1
    clear_cache
}

function assign_task() {
    echo -n "who? "
    read w
    $ASANACMD assign $1 $w
    read p
    clear_cache
}

function clear_cache() {
    rm -f ~/.asana.cache
}

function change_workspace() {
    clear
    $ASANACMD config
    clear_cache
}

function show_tasks() {
    clear
    $ASANACMD tasks | grep -v ":$"

    echo 
    echo "${CYAN}[ch]${RESET}ange workspace | ${CYAN}[r]${RESET}efresh | ${CYAN}[pro]${RESET}ject | ${CYAN}[cr]${RESET}eate task | ${CYAN}[number]${RESET}"
    echo -n "? "
    read r

    if [ "$r" = "" ]; then
        return 1
    fi
    docommand $r
}

function change_project() {
    clear
    $ASANACMD projects
}

function show_project_tasks() {
    clear
    clear_cache
    $ASANACMD pt
    echo "[number]"
    echo -n "? "
    read r

    if [ "$r" = "" ]; then
        clear_cache
        return 1
    fi
    dotasklistcommand $r $1
}

function dotasklistcommand() {
    if [[ $1 =~ [0-9].* ]]; then
        show_task $1
    fi
}

function create_task() {
    echo -n "name? "
    read name
    $ASANACMD ct --name "$name"
    clear_cache
}

function docommand() {
    case "$1" in
        "ch")
            change_workspace
            ;;
        "r")
            clear_cache
            ;;
        "pro")
            change_project
            while show_project_tasks; do
                clear
            done
            ;;
        "cr")
            create_task
            ;;
        *)
            if [[ $1 =~ [0-9].* ]]; then
                show_task $1
            fi
            ;;
    esac
}

main
